name: locales
description: Locale codes and ISO 4217 currency codes.
version: 0.0.2
author: Jacob Phillips <jifalops@gmail.com>
homepage: https://github.com/jifalops/locales

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:

dev_dependencies:
  test: ^1.3.3
  intl: ^0.15.7
